/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.io.File;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnMFI = new javax.swing.JButton();
        btnAFIC = new javax.swing.JButton();
        btnVFI = new javax.swing.JButton();
        btnVCO = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 480));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMIN HOMEPAGE MENU");
        jLabel2.setToolTipText("ADMIN HOMEPAGE MENU");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 60, 390, 33);

        btnMFI.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnMFI.setText("MODIFY FOOD ITEMS");
        btnMFI.setToolTipText("MODIFY FOOD ITEMS");
        btnMFI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMFIActionPerformed(evt);
            }
        });
        getContentPane().add(btnMFI);
        btnMFI.setBounds(200, 200, 300, 60);

        btnAFIC.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnAFIC.setText("ADD FOOD CATEGORY");
        btnAFIC.setToolTipText("ADD FOOD CATEGORY");
        btnAFIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAFICActionPerformed(evt);
            }
        });
        getContentPane().add(btnAFIC);
        btnAFIC.setBounds(200, 120, 300, 60);

        btnVFI.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnVFI.setText("VIEW FOOD ITEMS");
        btnVFI.setToolTipText("VIEW FOOD ITEMS");
        btnVFI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVFIActionPerformed(evt);
            }
        });
        getContentPane().add(btnVFI);
        btnVFI.setBounds(200, 280, 300, 60);

        btnVCO.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnVCO.setText("VIEW CUSTOMERS ORDERS");
        btnVCO.setToolTipText("VIEW CUSTOMERS ORDERS");
        btnVCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVCOActionPerformed(evt);
            }
        });
        getContentPane().add(btnVCO);
        btnVCO.setBounds(200, 360, 300, 60);

        jButton6.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jButton6.setText("EXIT");
        jButton6.setToolTipText("EXIT");
        jButton6.setActionCommand("exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(20, 90, 80, 40);

        jButton8.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jButton8.setText("BACK");
        jButton8.setToolTipText("VIEW CUSTOMERS ORDERS");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(20, 30, 80, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\Documents\\NetBeansProjects\\JavaAssignment\\src\\main\\java\\images\\adminmenubg.jpg")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(700, 500));
        jLabel1.setMinimumSize(new java.awt.Dimension(700, 500));
        jLabel1.setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 710, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMFIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMFIActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AdminMFI().setVisible(true);
    }//GEN-LAST:event_btnMFIActionPerformed

    private void closeIt(){

        this.getContentPane().setVisible(false);
        this.dispose();

    }

    private void btnAFICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAFICActionPerformed

        JFrame j = new JFrame();
        Object s = JOptionPane.showInputDialog(j, "Please Enter New Food Category Name: ", "Add Food Item Category", JOptionPane.INFORMATION_MESSAGE);

        String fileName = s.toString();
        fileName = fileName + ".txt";
     
        String path = "C:\\Users\\danie\\Documents\\NetBeansProjects\\JavaAssignment\\db\\" + fileName;
        File f = new File (path);
        try {
            if (f.createNewFile()) {
                JOptionPane.showMessageDialog(this,
                                        "Successfully Updated.",
                                        "Alert",
                                        JOptionPane.WARNING_MESSAGE);  
                System.out.println("File created.");
            } else {
                JOptionPane.showMessageDialog(this,
                                        "Please Enter The Required File!",
                                        "Add Food Item Category",
                                        JOptionPane.ERROR_MESSAGE);
                System.out.println("File already exists.");
            }       } catch (IOException ex) {
            Logger.getLogger(AdminMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAFICActionPerformed

    private void btnVFIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVFIActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AdminVFI().setVisible(true);
        
    }//GEN-LAST:event_btnVFIActionPerformed

    private void btnVCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVCOActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AdminVCO().setVisible(true);
    }//GEN-LAST:event_btnVCOActionPerformed

private JFrame frame;
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
//        System.exit(0);
        frame = new JFrame("exit");
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to exit?", "Admin Menu",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
           System.exit(0);
       }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        ADGUIDisplay ag = new ADGUIDisplay();
        ag.show(); //display second frame

        dispose(); //close current frame (JAGuiDisplay)
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAFIC;
    private javax.swing.JButton btnMFI;
    private javax.swing.JButton btnVCO;
    private javax.swing.JButton btnVFI;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
