/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Daniel
 */
public class AdminVFI extends javax.swing.JFrame {

    /**
     * Creates new form AdminVFI
     */
    public AdminVFI() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        TableVFI.getTableHeader().setFont(new Font("Poppins", Font.BOLD, 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableVFI = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        comboBoxViewFI = new javax.swing.JComboBox<>();
        btnClear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(216, 65, 65));
        jPanel1.setMaximumSize(new java.awt.Dimension(1500, 750));
        jPanel1.setMinimumSize(new java.awt.Dimension(713, 451));
        jPanel1.setLayout(null);

        TableVFI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Item Price (RM)"
            }
        ));
        TableVFI.setToolTipText("View Items Table");
        jScrollPane1.setViewportView(TableVFI);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 80, 409, 306);

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VIEW FOOD ITEMS");
        jLabel2.setToolTipText("VIEW FOOD ITEMS");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 30, 310, 37);

        jButton8.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jButton8.setText("BACK");
        jButton8.setToolTipText("BACK");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(530, 30, 80, 40);

        comboBoxViewFI.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        comboBoxViewFI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECT>", "Foods", "Drinks", "Desserts", "Snacks" }));
        comboBoxViewFI.setToolTipText("SELECT ITEMS");
        comboBoxViewFI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxViewFIActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxViewFI);
        comboBoxViewFI.setBounds(490, 150, 150, 40);

        btnClear.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setToolTipText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);
        btnClear.setBounds(510, 210, 110, 40);

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(470, 120, 190, 170);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

        Register rg = new Register();
        rg.setVisible(true);
        rg.pack();
        rg.setLocationRelativeTo(null);
        rg.setDefaultCloseOperation(Register.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        AdminMenu am = new AdminMenu();
        am.show(); //display second frame

        dispose(); //close current frame (JAGuiDisplay)
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model= (DefaultTableModel) TableVFI.getModel();
        model.setRowCount(0);


    }//GEN-LAST:event_btnClearActionPerformed

    private void comboBoxViewFIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxViewFIActionPerformed
        String selectedValue = comboBoxViewFI.getSelectedItem().toString();
        if (selectedValue.equals("Foods")) { 
            String filePath = "C:\\Users\\danie\\Documents\\NetBeansProjects\\JavaAssignment\\db\\Foods.txt";
            File file = new File(filePath);
        
            try {
                FileReader fr = new FileReader(file);
                BufferedReader br = new BufferedReader(fr);

                DefaultTableModel model = (DefaultTableModel)TableVFI.getModel();
                JTableHeader header = TableVFI.getTableHeader();
                header.setFont(new Font("Poppins", Font.BOLD, 20));
                header.setForeground(Color.BLACK);
                model.setRowCount(0);
                Object[] lines = br.lines().toArray();

                for(int i = 0; i < lines.length; i++){
                    String[] row = lines[i].toString().split(" ");
                    model.addRow(row);
                }

            } catch (FileNotFoundException ex) {
                System.out.println("Something went wrong");
            }
        
        
        } else if (selectedValue.equals("Drinks")){
            String filePath = "C:\\Users\\danie\\Documents\\NetBeansProjects\\JavaAssignment\\db\\Drinks.txt";
            File file = new File(filePath);

            try {
                FileReader fr = new FileReader(file);
                BufferedReader br = new BufferedReader(fr);

                DefaultTableModel model = (DefaultTableModel)TableVFI.getModel();
                JTableHeader header = TableVFI.getTableHeader();
                header.setFont(new Font("Poppins", Font.BOLD, 20));
                header.setForeground(Color.BLACK);
                model.setRowCount(0);
                Object[] lines = br.lines().toArray();

                for(int i = 0; i < lines.length; i++){
                    String[] row = lines[i].toString().split(" ");
                    model.addRow(row);
                }

            } catch (FileNotFoundException ex) {
                System.out.println("Something went wrong");
            }
            
        } else if (selectedValue.equals("Desserts")){
            String filePath = "C:\\Users\\danie\\Documents\\NetBeansProjects\\JavaAssignment\\db\\Desserts.txt";
            File file = new File(filePath);

            try {
                FileReader fr = new FileReader(file);
                BufferedReader br = new BufferedReader(fr);

                DefaultTableModel model = (DefaultTableModel)TableVFI.getModel();
                JTableHeader header = TableVFI.getTableHeader();
                header.setFont(new Font("Poppins", Font.BOLD, 20));
                header.setForeground(Color.BLACK);
                model.setRowCount(0);
                Object[] lines = br.lines().toArray();

                for(int i = 0; i < lines.length; i++){
                    String[] row = lines[i].toString().split(" ");
                    model.addRow(row);
                }

            } catch (FileNotFoundException ex) {
                System.out.println("Something went wrong");
            }
        
        } else if (selectedValue.equals("Snacks")){
            String filePath = "C:\\Users\\danie\\Documents\\NetBeansProjects\\JavaAssignment\\db\\Snacks.txt";
            File file = new File(filePath);

            try {
                FileReader fr = new FileReader(file);
                BufferedReader br = new BufferedReader(fr);

                DefaultTableModel model = (DefaultTableModel)TableVFI.getModel();
                JTableHeader header = TableVFI.getTableHeader();
                header.setFont(new Font("Poppins", Font.BOLD, 20));
                header.setForeground(Color.BLACK);
                model.setRowCount(0);
                Object[] lines = br.lines().toArray();

                for(int i = 0; i < lines.length; i++){
                    String[] row = lines[i].toString().split(" ");
                    model.addRow(row);
                }

            } catch (FileNotFoundException ex) {
                System.out.println("Something went wrong");
            }

        }  else if (selectedValue.equals("<SELECT>")){  

            JOptionPane.showMessageDialog(this,
                                    "Please Select A Food Category!",
                                    "View Food Items",
                                    JOptionPane.ERROR_MESSAGE);
            } 
    }//GEN-LAST:event_comboBoxViewFIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminVFI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminVFI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminVFI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminVFI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminVFI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableVFI;
    private javax.swing.JButton btnClear;
    private javax.swing.JComboBox<String> comboBoxViewFI;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
